---
- hosts: all
  become: yes
  tasks:
  # Composer
  - name: PHP | Install Composer
    shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
    args:
      warn: no
      creates: /usr/local/bin/composer