---
- hosts: all
  become: yes
  tasks:

  - name: NodeJS | Install NodeJS apt key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: NodeJS | Install NodeJS repository
    apt_repository:
      repo: deb https://deb.nodesource.com/node_10.x bionic main
      state: present

  - name: NodeJS | Install yarn apt key
    apt_key:
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present

  - name: NodeJS | Install yarn repository
    apt_repository:
      repo: deb https://dl.yarnpkg.com/debian/ stable main
      state: present

  - name: NodeJS | install packages
    apt:
      name: ['nodejs', 'npm', 'yarn']
      state: latest
      update_cache: yes

      #npm --version
      #node --version
      #yarn --version
